## Configuration for Alacritty, the GPU enhanced terminal emulator.
## It's a very basic and simple config file, for full configuration...
## See, /usr/share/doc/alacritty/example/alacritty.yml

## Import files (Colors, Fonts, Etc)
import:
  # - ~/.config/alacritty/colorschemes/Campbell.yaml
  # - ~/.config/alacritty/themes/seashells.yaml
  - ~/.config/alacritty/colorschemes/Solarized_dark.yaml
  - ~/.config/alacritty/fonts.yml

## Set environment variables
env:
  TERM: alacritty
  WINIT_X11_SCALE_FACTOR: "1.0"

## Terminal window settings
window:
  dimensions:
    columns: 110
    lines: 25

  padding:
    x: 6
    y: 6

  decorations: full
  startup_mode: Windowed
  dynamic_title: true

  ## scrolling
  history: 10000
  multiplier: 3

## Background opacity
window:
   opacity: 0.77

## Cursor
cursor:
  style:
    shape: Block
    blinking: On

  unfocused_hollow: false

## Live config reload
live_config_reload: true
